### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Brances** [12207480/LovePlayNews#1]
This version does not support documents saved in the Xcode 8 format. Open this document with Xcode 8.0

**Comment by Brances** [comment]
打开xib中的代码，删除`<capabilityname="documents saved in the Xcode 8 format"minToolsVersion="8.0"/>`

**Comment by 12207480** [comment]
用xcode8 打开后 以前的xcode版本打开会有这个问题

**Comment by Brances** [comment]
@12207480  能给个博客地址吗 。

**Comment by 12207480** [comment]
😄木有

**Comment by Brances** [comment]
@12207480  不过找到了你的微博。
