### ISSUE TITLE
你好，导航栏 tab 变多的时候显示就出问题了

### ISSUE THREAD

**Issue by ganjmeng** [12207480/LovePlayNews#2]
你好，导航栏 tab 变多的时候显示就出问题了，我看那个TYPagerController标签多的时候可以水平滚动的，那个属性怎么设置的，求解，谢谢大神！
![img_2233](https://cloud.githubusercontent.com/assets/12026835/20050380/04f165d6-a504-11e6-8506-a2036fda5d81.PNG)

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/20050547/e031ade0-a504-11e6-9ebb-92e4bc5b4b69.png)
cell pace 设置固定值就可以了

**Comment by ganjmeng** [comment]
知道了，我试试，多谢
