### ISSUE TITLE
Undefined symbols for architecture x86_64 _ASPagerFlowLayout

### ISSUE THREAD

**Issue by andykimisgreat** [12207480/LovePlayNews#4]
项目build出错。XCode 7.3.
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASPagerFlowLayout", referenced from:
      objc-class-ref in LPImagePagerCellNode.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by 12207480** [comment]
换xcode8吧

**Comment by jasonpp** [comment]
Can't start it up , and have always stop on this point " **[self showADImageWithURL:[NSURL URLWithString:imageURL]]**;"Why? Is your service has some mistakes or something else?PLZ debug it asap,appreciate.

**Comment by jasonpp** [comment]
I copy this ---> http://i.play.163.com/user/article/list/  in the address of the website,the response is--->
**{"code":404,"message":"找不到资源"}** ------>Why would show these?

**Comment by 12207480** [comment]
fixed this bug
