### ISSUE TITLE
关于controller缓存失效问题

### ISSUE THREAD

**Issue by EMAPvector** [12207480/LovePlayNews#8]
你好，我发现在模拟器模拟一次内存警告，controller便不会再缓存了。我找了一些资料可能是因为在didReceiveMemoryWarning中调用了removeAllObjects导致NSCache失效，不知是不是这个原因

**Comment by 12207480** [comment]
收到

**Comment by 12207480** [comment]
哪个？TYPagerController？

**Comment by 12207480** [comment]
已修复
